backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/img/blogs/uploads"
public_folder: "uploads"


collections:
  - label: "Pages Settings"
    name: "pages"
    files:
      - label: "About Page"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "about landing page"
            name: "headerAbout"
            widget: "object"
            fields:
              - {label: "Header Catch Phrase", name: "catch_phrase", widget: "string"}
              - {label: "Header subtext", name: "subtext", widget: "string"}
              - {label: "Box One Heading", name: "info_box_1_heading", widget: "string"}
              - {label: "Box One subtext", name: "info_box_1_subtext", widget: "string"}
              - {label: "Box Two Heading", name: "info_box_2_heading", widget: "string"}
              - {label: "Box Two subtext", name: "info_box_2_subtext", widget: "string"}
              - {label: "Box Three Heading", name: "info_box_3_heading", widget: "string"}
              - {label: "Box Three subtext", name: "info_box_3_subtext", widget: "string"}
      - label: "About Me Page"
        name: "aboutme"
        file: "_data/aboutme.yml"
        fields:
          - label: "about Me landing page"
            name: "headerAboutMe"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Blurb", name: "blurp", widget: "string"}
              - {label: "my Story", name: "myStory", widget: "markdown"}
      - label: "Home Page"
        name: "index"
        file: "_data/index.yml"
        widget: 'object'
        fields:
          - label: "Header Section"
            name: "home"
            widget: "object"
            fields:
              - {label: "First Catch Phrase", name: "header_catch_phrase_one", widget: "string"}
              - {label: "Second Catch Phrase", name: "header_catch_phrase_two", widget: "string"}
              - {label: "Blurb", name: "header_paragraph", widget: "string"}
              - label: "About Section"
                name: "home"
                widget: "object"
                fields:
                  - {label: "Small Title", name: "about_title_one", widget: "string"}
                  - {label: "Heading Title", name: "about_heading", widget: "string"}
                  - {label: "about paragraph", name: "about_paragraph", widget: "string"}
                  - {label: "First Box Title", name: "about_box_one_title", widget: "string"}
                  - {label: "First Box paragraph", name: "about_box_one_p", widget: "string"}
                  - {label: "Second Box Title", name: "about_box_two_title", widget: "string"}
                  - {label: "Second Box paragraph", name: "about_box_two_p", widget: "string"}
                  - {label: "Third Box Title", name: "about_box_three_title", widget: "string"}
                  - {label: "Third Box paragraph", name: "about_box_three_p", widget: "string"}
                  - {label: "Fourth Box Title", name: "about_box_four_title", widget: "string"}
                  - {label: "Fourth Box paragraph", name: "about_box_four_p", widget: "string"}

